#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
File Name	: Camera_Detecting
Author		: WuLian
Data		: 2016-5-31
Description	:
	检测摄像头监控的图像是否有改变。可以用于安防监控，有人潜入会报警。
	程序思路就是由摄像头先后获取两张图片，做减法后统计不为零的像素点所占比例，在本例程中比例设为50%，
	即超过50%就认为两个时间点的图片不一样，打印"changed!!!"，否则打印"none changed!!!"，另外点击
	鼠标左键会视频截图。
'''
import SimpleCV
import numpy as np
import time

cap = SimpleCV.Camera()
display = SimpleCV.Display()


while not display.isDone():
	imagePre = cap.getImage()
	time.sleep(0.05)
	imageAft = cap.getImage()
	diff = imagePre - imageAft

	matrix = diff.getNumpy()
	flat = matrix.flatten()

	num_change = np.count_nonzero(flat)
	percent_change = float(num_change) / float(len(flat))

	if percent_change > 0.5:
		print "changed ! ! ! "
	else:
		print "none change ! ! !"


	diff.save(display)
	if display.mouseLeft:
		imagePre.save("test.png")
