#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
File Name	: Camera
Author		: WuLian
Data		: 2016-5-31
Description	: a simple camera program
'''
import cv2

print("这是一个测试程序，请输入操作对应数字，回车确定：")
print("1、显示本地图片：")
print("2、照相机：")
print("3、播放本地视频")
print("4、摄像头录取视频并保存到本地：")
switch = raw_input()
if switch == '1':
	picture_path = raw_input("请输入图片所在路径(比如/home/picture.jpg)\n")
	print("'q'键退出窗口")
	img = cv2.imread(picture_path,0)
	cv2.namedWindow("test",cv2.WINDOW_NORMAL)
	cv2.imshow("test",img)
	key = cv2.waitKey(0)
	if key == ord('q')  :
		cv2.destroyAllWindows()
elif switch == '2':
	print("'q'键退出窗口，‘s’键保存照片")
	cap = cv2.VideoCapture(0)
	cv2.namedWindow("camera",cv2.WINDOW_NORMAL)
	while(True):
		ret,frame = cap.read()
		if ret == True:
			cv2.imshow("camera", frame)
			key = cv2.waitKey(1)
			if key == ord('q'):
				break;
			elif key == ord('s'):
				picture_path = raw_input("请输入照片存放路径，比如/home/picture.jpg\n")
				cv2.imwrite(picture_path, frame)
				break;
	cap.release()
	cv2.destroyAllWindows()
elif switch == '3':
	video_path = raw_input("请输入视频所在路径，比如/home/video.mp4\n")
	print("'q'键退出窗口")
	cap = cv2.VideoCapture(video_path)
	cv2.namedWindow("video",cv2.WINDOW_NORMAL)
	while(True):
		ret,frame = cap.read()
		if ret == True:
			cv2.imshow("video", frame)
			key = cv2.waitKey(25)
			if key == ord('q'):
				break;
	cap.release()
	cv2.destroyAllWindows()
elif switch == '4':
	print("‘q’键退出当前窗口")
	video_path = raw_input("请输入视频存放路径：\n")
	cap = cv2.VideoCapture(0)
	fourcc = cv2.cv.FOURCC(*'XVID')
	out = cv2.VideoWriter(video_path,fourcc,20.0,(640,480))
	cv2.namedWindow("video")
	while(True):
		ret,frame = cap.read()
		if ret == True:
			out.write(frame)
			cv2.imshow("video",frame)
			key = cv2.waitKey(1)
			if key == ord('q'):
				break;
	cap.release()
	out.release()
	cv2.destroyAllWindows()
else:
	print("干哈呢你？请重新输入1～4：")
